// 활동 타입 상수 정의
export const ACTIVITY_TYPES = {
  // 수강 신청 관련
  ENROLLMENT: {
    ENROLL_SESSION: 'ENROLL_SESSION', // 개별 세션 신청
    BATCH_ENROLL_SESSIONS: 'BATCH_ENROLL_SESSIONS', // 배치 세션 신청
    CANCEL_ENROLLMENT: 'CANCEL_ENROLLMENT', // 수강 취소
    CHANGE_ENROLLMENT: 'CHANGE_ENROLLMENT', // 수강 변경 (취소 + 신청)
    CHANGE_SCHEDULE: 'CHANGE_SCHEDULE', // 스케줄 변경
    APPROVE_ENROLLMENT: 'APPROVE_ENROLLMENT', // 수강 승인
    REJECT_ENROLLMENT: 'REJECT_ENROLLMENT', // 수강 거부
    UPDATE_ENROLLMENT_STATUS: 'UPDATE_ENROLLMENT_STATUS', // 상태 변경
    BATCH_APPROVE_ENROLLMENT: 'BATCH_APPROVE_ENROLLMENT', // 배치 승인
    BATCH_REJECT_ENROLLMENT: 'BATCH_REJECT_ENROLLMENT', // 배치 거부
    BATCH_UPDATE_ENROLLMENT_STATUS: 'BATCH_UPDATE_ENROLLMENT_STATUS', // 배치 상태 변경
    COMPLETE_ENROLLMENT: 'COMPLETE_ENROLLMENT', // 수업 완료
  },

  // 결제 관련
  PAYMENT: {
    PAYMENT_ATTEMPT: 'PAYMENT_ATTEMPT', // 결제 시도
    PAYMENT_COMPLETED: 'PAYMENT_COMPLETED', // 결제 완료
    PAYMENT_FAILED: 'PAYMENT_FAILED', // 결제 실패
    PAYMENT_CANCELLED: 'PAYMENT_CANCELLED', // 결제 취소
    REFUND_REQUEST: 'REFUND_REQUEST', // 환불 요청
    REFUND_COMPLETED: 'REFUND_COMPLETED', // 환불 완료
    REFUND_REJECTED: 'REFUND_REJECTED', // 환불 거부
    PARTIAL_REFUND: 'PARTIAL_REFUND', // 부분 환불
  },

  // 출석 관련
  ATTENDANCE: {
    ATTENDANCE_CHECK: 'ATTENDANCE_CHECK', // 출석 체크
    ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE', // 출석 수정
    LATE_ATTENDANCE: 'LATE_ATTENDANCE', // 지각 처리
    ABSENT_ATTENDANCE: 'ABSENT_ATTENDANCE', // 결석 처리
  },

  // 계정 관련
  ACCOUNT: {
    LOGIN: 'LOGIN', // 로그인
    LOGOUT: 'LOGOUT', // 로그아웃
    SIGNUP: 'SIGNUP', // 회원가입
    PROFILE_UPDATE: 'PROFILE_UPDATE', // 프로필 수정
    PASSWORD_CHANGE: 'PASSWORD_CHANGE', // 비밀번호 변경
    ACCOUNT_DELETION: 'ACCOUNT_DELETION', // 계정 탈퇴
  },

  // 클래스 관리
  CLASS: {
    CLASS_CREATE: 'CLASS_CREATE', // 클래스 생성
    CLASS_UPDATE: 'CLASS_UPDATE', // 클래스 수정
    CLASS_DELETE: 'CLASS_DELETE', // 클래스 삭제
    CLASS_STATUS_CHANGE: 'CLASS_STATUS_CHANGE', // 클래스 상태 변경
    CLASS_SESSION_CREATE: 'CLASS_SESSION_CREATE', // 세션 생성
    CLASS_SESSION_UPDATE: 'CLASS_SESSION_UPDATE', // 세션 수정
    CLASS_SESSION_DELETE: 'CLASS_SESSION_DELETE', // 세션 삭제
  },

  // 학원 관련
  ACADEMY: {
    ACADEMY_JOIN: 'ACADEMY_JOIN', // 학원 가입
    ACADEMY_LEAVE: 'ACADEMY_LEAVE', // 학원 탈퇴
    ACADEMY_UPDATE: 'ACADEMY_UPDATE', // 학원 정보 수정
  },

  // 관리자 활동
  ADMIN: {
    ROLE_CHANGE: 'ROLE_CHANGE', // 권한 변경
    SYSTEM_CONFIG_CHANGE: 'SYSTEM_CONFIG_CHANGE', // 시스템 설정 변경
    NOTICE_CREATE: 'NOTICE_CREATE', // 공지사항 작성
    NOTICE_UPDATE: 'NOTICE_UPDATE', // 공지사항 수정
    NOTICE_DELETE: 'NOTICE_DELETE', // 공지사항 삭제
    BATCH_SESSION_COMPLETE: 'BATCH_SESSION_COMPLETE', // 배치 세션 완료 처리
  },
} as const;

// 활동 타입을 평면화
export const ALL_ACTIVITY_TYPES = Object.values(ACTIVITY_TYPES).reduce(
  (acc, category) => {
    return { ...acc, ...category };
  },
  {},
);

// 엔티티 타입 정의
export const ENTITY_TYPES = {
  SESSION_ENROLLMENT: 'SESSION_ENROLLMENT',
  PAYMENT: 'PAYMENT',
  ATTENDANCE: 'ATTENDANCE',
  CLASS: 'CLASS',
  CLASS_SESSION: 'CLASS_SESSION',
  ACADEMY: 'ACADEMY',
  USER: 'USER',
  NOTICE: 'NOTICE',
} as const;
