name: Test Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Step
        run: |
          echo "GitHub Actions is working!"
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
